apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: update
  name: update
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8080
  selector:
    io.kompose.service: update
